page_blocks: []
_array_structures:
  page_blocks:
    - label: Banner
      icon: ballot
      value:
        _id: banner
        background_image:
        block-class:
        heading:
        sub-heading:
        link-text:
        link_url:
    - label: CTA
      icon: format_quote
      value:
        _id: cta
        block-class:
        heading:
        description:
        link-text:
        link_url:
    - label: Two Col
      icon: format_quote
      value:
        _id: two-col
        block-class:
        col-1_html:
        col-2_html:
